# Generated by Django 2.1.12 on 2019-10-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_remove_myuser_is_catt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='name',
            new_name='username',
        ),
    ]
