# Generated by Django 2.1.12 on 2019-10-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_auto_20191010_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='catt',
            new_name='is_catt',
        ),
    ]
