# Generated by Django 2.1.12 on 2019-10-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_auto_20191010_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_catt',
            field=models.BooleanField(default=False),
        ),
    ]
