# Generated by Django 2.1.12 on 2019-10-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_myuser_is_catt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_lock',
        ),
    ]
