# Generated by Django 2.1.12 on 2019-10-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_remove_myuser_is_lock'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
    ]
