# Generated by Django 2.1.12 on 2019-10-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_myuser_is_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='gioi_tinh',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_catt',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_lock',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_name',
        ),
    ]
